Repository survey-mate/backend, pull requests merged in 2024-02, with the labels that each got.

#86 Fix/85
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/converter/AuthConverter.java
  src/main/java/uk/jinhy/survey_mate_api/common/email/service/MailService.java
Labels: fix

#87 feat: 닉네임 중복 시 409 에러 응답 #68
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/MemberRepository.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
Labels: feat

#89 feat: 닉네임 중복 api 추가 #88
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
Labels: feat

#104 fix: 설문장터 API 에러 수정 #103
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/converter/DataConverter.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/dto/DataControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/StatementController.java
Labels: fix

#105 fix: 설문장터 API 수정 #103
  src/main/java/uk/jinhy/survey_mate_api/common/aws/S3Service.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/dto/DataServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/repository/DataRepository.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/converter/DataConverter.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/dto/DataControllerDTO.java
Labels: fix

#108 build: ECS로 마이그레이션 #107
  .aws/task-definition.json
  .github/workflows/cd.yml
  Dockerfile
  appspec.yml
  gradlew
  script/deploy.sh
Labels: build

#111 refactor: Survey 패키지 리팩토링
  src/main/java/uk/jinhy/survey_mate_api/survey/application/dto/SurveyCommandServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyCommandService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyCommandServiceImpl.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyQueryService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyQueryServiceImpl.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacadeImpl.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/SurveyController.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/converter/SurveyConverter.java
Labels: refactor

#115 feat: 이메일 전송 기능 복구 #114
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/common/email/service/dto/MailServiceDTO.java
  src/main/resources/templates/SurveyEmail.html
Labels: feat

#119 refactor: API 응답 와일드카드 제거 #117
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/StatementController.java
Labels: refactor

#120 fix: Statement API 로직 수정 #118
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
  src/main/java/uk/jinhy/survey_mate_api/statement/domain/entity/Statement.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/StatementController.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/converter/StatementConverter.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/dto/StatementControllerDTO.java
Labels: fix

#122 feat: 닉네임 수정 api 추가 #121
  src/main/java/uk/jinhy/survey_mate_api/auth/application/dto/AuthServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/converter/AuthConverter.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
Labels: feat

#126 chore: jwt 환경변수 설정 #124
  src/main/resources/application.yml
Labels: chore

#128 fix: 메일 전송 실패 오류 500으로 번경 #125
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
Labels: fix

#134 chore: ddl update로 수정 #133
  src/main/resources/application.yml
Labels: chore

#137 Chore/136
  src/main/java/uk/jinhy/survey_mate_api/auth/infrastructure/AuthProviderImpl.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/EmailConfig.java
  src/main/resources/application.yml
Labels: chore

#135 fix: Data Statement 최신 목록 조회 쿼리 수정 #132
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/repository/DataRepository.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
  src/main/java/uk/jinhy/survey_mate_api/statement/domain/repository/StatementRepository.java
Labels: fix

#145 feat: 프로필 확인 API 추가
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
Labels: feat

#159 fix: 비밀번호 오류 시 로그인 가능 버그 수정 #158
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
Labels: fix

#162 fix: 설문장터 삭제된 데이터 조회 수정 #161
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/repository/DataRepository.java
Labels: fix

#165 feat: 예외 처리 추가
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacadeImpl.java
Labels: feat

#168 fix: 회원 탈퇴 postmapping으로 수정 #167
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
Labels: fix

#171 hotfix: auth/nickname api 보안 수정
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
Labels: hotfix

#173 hotfix: yml 한글 세팅 #172
  src/main/resources/application.yml
Labels: hotfix

#177 hotfix: 닉네임 중복 확인 requestParam으로 수정 #176
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
Labels: hotfix

#180 이화여대 도메인 추가 + 회원가입 축하 포인트 100으로 수정
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
Labels: hotfix
