Repository survey-mate/backend, pull requests merged in 2024-01, with the labels that each got.

#2 build: build.gradle dependencies 설정 #1
  build.gradle
  src/main/resources/application.yml
Labels: build

#7 build: 파이프라인 수정 #6
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: build

#9 chore: S3, Spring Security, Swagger 설정 추가 #8
  build.gradle
  src/main/java/uk/jinhy/survey_mate_api/common/config/S3Config.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/test/java/uk/jinhy/survey_mate_api/DemoApplicationTests.java
Labels: chore

#13 build: deploy.sh 실행 훅 추가 #12
  appspec.yml
Labels: build

#15 Feat/14
  src/main/java/uk/jinhy/survey_mate_api/answer/Answer.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
  src/main/java/uk/jinhy/survey_mate_api/data/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data_comment/DataComment.java
  src/main/java/uk/jinhy/survey_mate_api/deviceToken/DeviceToken.java
  src/main/java/uk/jinhy/survey_mate_api/member/Member.java
  src/main/java/uk/jinhy/survey_mate_api/notification/Notification.java
  src/main/java/uk/jinhy/survey_mate_api/purchaseHistory/PurchaseHistory.java
  src/main/java/uk/jinhy/survey_mate_api/statement/Statement.java
  src/main/java/uk/jinhy/survey_mate_api/survey/Survey.java
  src/main/java/uk/jinhy/survey_mate_api/survey/SurveyStatus.java
  src/main/java/uk/jinhy/survey_mate_api/surveyComment/SurveyComment.java
  src/main/resources/application.yml
Labels: feat

#24 feat: Util.generateRandomString
  src/main/java/uk/jinhy/survey_mate_api/common/util/Util.java
Labels: feat

#22 feat: API 공통 응답 추가 #21
  src/main/java/uk/jinhy/survey_mate_api/common/response/ApiResponse.java
Labels: feat

#26 feat: 에러 헨들러 구현
  src/main/java/uk/jinhy/survey_mate_api/common/response/Body.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/exception/ExceptionAdvice.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/exception/GeneralException.java
Labels: feat

#27 feat: Survey 도메인 및 SurveyService 일부 구현
  src/main/java/uk/jinhy/survey_mate_api/member/Member.java
  src/main/java/uk/jinhy/survey_mate_api/survey/SurveyStatus.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/dto/SurveyServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Answer.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Survey.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/SurveyComment.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/repository/SurveyRepository.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/SurveyController.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/converter/SurveyConverter.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/dto/SurveyControllerDTO.java
Labels: feat

#30 feat: Data 도메인 및 DataService 일부 구현 #28
  src/main/java/uk/jinhy/survey_mate_api/data/application/dto/DataServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/PurchaseHistory.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/repository/DataRepository.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/converter/DataConverter.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/dto/DataControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/data_comment/DataComment.java
  src/main/java/uk/jinhy/survey_mate_api/member/Member.java
Labels: feat

#32 feat: 회원가입, 로그인 일부 구현 #25
  build.gradle
  src/main/java/uk/jinhy/survey_mate_api/auth/application/dto/AuthServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/MemberRepository.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/LoginControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/MemberControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/auth/AuthProvider.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SwaggerConfig.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/exception/ExceptionAdvice.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/PurchaseHistory.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/repository/DataRepository.java
  src/main/java/uk/jinhy/survey_mate_api/data_comment/DataComment.java
  src/main/java/uk/jinhy/survey_mate_api/deviceToken/DeviceToken.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/CustomAuthenticationProvider.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/JwtAccessDeniedHandler.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/JwtAuthenticationFilter.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/JwtConfig.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/JwtTokenProvider.java
  src/main/java/uk/jinhy/survey_mate_api/jwt/UserDetailsServiceImpl.java
  src/main/java/uk/jinhy/survey_mate_api/notification/Notification.java
  src/main/java/uk/jinhy/survey_mate_api/statement/Statement.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Answer.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Survey.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/SurveyComment.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/repository/SurveyRepository.java
  src/main/resources/application.yml
Labels: feat

#34 feat: Survey API 구현
  src/main/java/uk/jinhy/survey_mate_api/SurveyMateApplication.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyRegistrationFee.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Survey.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/repository/SurveyRepository.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/SurveyController.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/converter/SurveyConverter.java
  src/main/java/uk/jinhy/survey_mate_api/survey/presentation/dto/SurveyControllerDTO.java
Labels: feat

#35 feat: 이메일 인증 API 추가 #33
  build.gradle
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/MailService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/EmailToken.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/MailCode.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/EmailTokenRepository.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/MailCodeRepository.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/MemberRepository.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/MailCodeControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/MailControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/MemberControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/EmailConfig.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
  src/main/resources/application.yml
  src/main/resources/images/logo.png
  src/main/resources/templates/SurveyEmail.html
Labels: feat

#41 feat: 포인트 API - 응답 DTO 구현 및 AuthService와 연결 #29
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/StatementController.java
  src/main/java/uk/jinhy/survey_mate_api/statement/presentation/dto/StatementControllerDTO.java
Labels: feat

#42 feat: 설문장터 API Controller 부분 구현
  src/main/java/uk/jinhy/survey_mate_api/common/aws/S3Service.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/S3Config.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/dto/DataServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/DataController.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/converter/DataConverter.java
  src/main/java/uk/jinhy/survey_mate_api/data/presentation/dto/DataControllerDTO.java
  src/main/resources/application.yml
Labels: feat

#45 Refactor/44
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Password.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/PasswordValidator.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/StudentEmail.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/StudentEmailValidator.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
Labels: refactor

#50 refactor: 필요없는 코드, 클래스 삭제 #46
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/data/domain/entity/Data.java
  src/main/java/uk/jinhy/survey_mate_api/data_comment/DataComment.java
  src/main/java/uk/jinhy/survey_mate_api/deviceToken/DeviceToken.java
  src/main/java/uk/jinhy/survey_mate_api/notification/Notification.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/Survey.java
  src/main/java/uk/jinhy/survey_mate_api/survey/domain/entity/SurveyComment.java
Labels: refactor

#51 refactor: auth 부분 DTO 수정 #47
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
Labels: refactor

#53 feat: 계정 삭제 api 추가 #52
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/response/Status.java
Labels: feat

#55 fix: 전체 포인트 null 반환 에러 수정 #29
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
  src/main/java/uk/jinhy/survey_mate_api/statement/domain/repository/StatementRepository.java
Labels: fix

#56 refactor: 회원가입 로직 수정, member 엔티티 칼럼 추가, 학생계정 확인 api 추가 #54
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/Member.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/StudentEmail.java
  src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/StudentEmailValidator.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
Labels: refactor, feat

#58 fix: Statement 엔티티 Notnull 에러 해결 #29
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
Labels: fix

#64 chore: 실제 메일 전송 대신 임시 responseDTO로 인증코드 전달 #63
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/CodeResponseDTO.java
Labels: chore

#69 refactor: 포인트 지급 차감
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataServiceFacade.java
  src/main/java/uk/jinhy/survey_mate_api/statement/application/dto/StatementServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/statement/application/service/StatementService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyServiceFacade.java
Labels: refactor

#71 refactor: Util 중복 메소드 제거, 개선
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/CreateCodeUtil.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/CreateRandomStringUtil.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/Util.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyService.java
Labels: refactor

#77 fix: 비밀번호 재설정 시 인증 필요 없도록 수정 #76
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
Labels: fix

#78 Revert "refactor: Util 중복 메소드 제거, 개선"
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/CreateCodeUtil.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/CreateRandomStringUtil.java
  src/main/java/uk/jinhy/survey_mate_api/common/util/Util.java
  src/main/java/uk/jinhy/survey_mate_api/data/application/service/DataService.java
  src/main/java/uk/jinhy/survey_mate_api/survey/application/service/SurveyService.java
Labels: refactor, hotfix

#81 Refactor/74
  src/main/java/uk/jinhy/survey_mate_api/auth/application/dto/AuthServiceDTO.java
  src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
  src/main/java/uk/jinhy/survey_mate_api/auth/presentation/converter/AuthConverter.java
  src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
  src/main/java/uk/jinhy/survey_mate_api/common/jwt/AuthenticationProviderImpl.java
Labels: feat
